### PR TITLE
Install pcntl extension for magento2 images

### PR DESCRIPTION
**Pull request by ihor-sviziev**

### CODE REVIEW

**Comment by drpayyne** [comment]
Thanks for the PR, @ihor-sviziev! 

What's the reason to include this PHP extension? I don't see it as a requirement in https://devdocs.magento.com/guides/v2.4/install-gde/prereq/php-settings.html.

**Comment by drpayyne** [comment]
Should this extension be needed, I think https://github.com/drpayyne/docker-php/blob/debian/fpm/Dockerfile#L14 is a better place. Now that I see that file, the line your PR can be removed entirely since the existing two extensions are already installed over there.

**Comment by ihor-sviziev** [comment]
@drpayyne for some reason, I was able to create a commit https://github.com/drpayyne/docker-php/commit/18ea280e6dff150d6b1b45d12824c8ab64252df3

The reason why this extension is needed - it's used in many places in Magento as an optional thing, but it improves static content deploy and indexation speeds https://github.com/magento/magento2/search?q=pcntl

**Comment by drpayyne** [comment]
Thanks @ihor-sviziev! It's because you're already a collaborator on that repo. :)

**Comment by ihor-sviziev** [comment]
@drpayyne, could you please set up re-building PHP images automatically, for instance once a month, similar to what original warden repo does?

**Comment by drpayyne** [comment]
I did consider that, but decided to keep only manual triggers as this repo isn't updated as much as the original warden. So I felt it better not to have new images every month if there are no changes, don't you think?

**Comment by ihor-sviziev** [comment]
@drpayyne, security updates for installed packages, including composer version are not updated if you're not building the image

**Comment by ihor-sviziev** [comment]
Hi @drpayyne,
I see that the new images are still not available. Could you please build them?

**Comment by ihor-sviziev** [comment]
@drpayyne ?

**Comment by drpayyne** [comment]
Hi @ihor-sviziev, I'm on leave at the moment, so I can take a look at this next week.

**Comment by ihor-sviziev** [comment]
Sure, just thought my message got lost.

**Pull request merged**
